### ISSUE TITLE
Char LCD / 7-segment display

### ISSUE THREAD

**Issue by dtran76** [Smart-Track/mbed-program#6]
A character LCD for the starting line. Can be used to display current lap, player name, race name, etc. 

- [x] Find an Mbed library
- [x] Print text from Mbed to the LCD
- [x] Implement into race code

**Comment by dtran76** [comment]
Char LCD has a I2C expansion board on the back. Can't find a library for it for Mbed. May have to give up the char LCD and use 7-segment displays instead.

Alternative, we can desolder the board and control the LCD directly, but it requires 10 pins, leaving us with only 1 spare.
Edit: or run the LCD in 4-bit mode for only 6 pins (4 data, 1 enable, 1 register select)

**Comment by dtran76** [comment]
Unable to find a working library for the char LCD. We will use a 4 digit 7-segment display instead.

**Comment by glanier9** [comment]
We were able to find a working library for a generic 7SD. Implemented for countdown. Closing issue.
